spring.application.name=inka-productos
server.port=8081

# Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/erp_productos?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# JWT — clave fija (min 32 caracteres para HS256)
jwt.secret=InkaProductosERP2024SecretKeyJWT!!

# Logs
logging.level.pe.cibertec=INFO
logging.level.org.springframework.security=WARN
